### PR TITLE
support non semantic Rasa image tags

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed Changes**:
- fix https://github.com/RasaHQ/rasa-x-helm/issues/86
- introduce a new `.rasa.version` value which is used to the version checks to ensure backward compatibility. This is only used to construct the image tag in case `.Values.rasa.tag` is empty. If `Values.rasa.tag` is empty, a template constructs an image name `{.Values.rasa.version}-full` by default.

### CODE REVIEW

**Comment by wochinge** [comment]
@loomsen I can't tag you for review, but please have a look as well 👍

**Review by tczekajlo — APPROVED** [review]
Thanks a lot for taking care of it! 🙌   LGTM 🚀  (there is an issue with the lint check 😄 )

**Comment by loomsen** [comment]
@wochinge I like it, LGTM. Thank you!

**Review by tczekajlo — APPROVED** [review]
🚀

**Comment by wochinge** [comment]
> Thanks a lot for taking care of it!

It was a please :-) Feel free to assign me DevOps issues every now and then!

**Pull request merged**
