### PR TITLE
Bump Rasa X version to 0.41.2

### PR DESCRIPTION
**Pull request by rasabot**

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @TyDunn will take a look at it as soon as possible ✨

**Comment by TyDunn** [comment]
@erohmensing who should I hand this off to?

**Comment by erohmensing** [comment]
Oh weird, I wouldn't expect it to answer these, thanks for pinging, we'll take care of it

**Comment by erohmensing** [comment]
@tczekajlo do we need to bump the `version` when we bump the `appVersion`?

**Comment by tczekajlo** [comment]
> @tczekajlo do we need to bump the `version` when we bump the `appVersion`?

Yes, the version has to be bump as well, otherwise, it won't release. anew package.

**Review by tczekajlo — APPROVED** [review]
LGTM

**Pull request merged**
