### PR TITLE
Separate annotations for rasa services and use correct url for rasa-worker

### PR DESCRIPTION
**Pull request by erohmensing**
- make it possible to annotate services separately, as they need their own ssl certificates. 
- correct the rasa-worker URL so that the ssl cert for it is valid.

### CODE REVIEW

**Comment by tczekajlo** [comment]
@erohmensing Is it ready to review? There is one check failed

**Comment by erohmensing** [comment]
It's only the check i mentioned before that usually fails multiple times and i have to restart it and then it works

**Comment by erohmensing** [comment]
ready now 🙂

**Review by tczekajlo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
