### PR TITLE
prepare rename to 'main'

### PR DESCRIPTION
**Pull request by wochinge**
- follow-up of https://github.com/RasaHQ/rasa/issues/6028
- rename old `master` occurrences to `main`

### CODE REVIEW

**Comment by wochinge** [comment]
We unfortunately can't rename [this](https://github.com/RasaHQ/rasa-x-helm/blob/9eb63cb275c4a0957f3d8a8bab0d4a98f4da1483/charts/rasa-x/templates/_redis.tpl#L13) due to how Bitnami names the service [here](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-master-svc.yaml)

**Comment by wochinge** [comment]
seems my PR depends on https://github.com/RasaHQ/rasa-x-helm/pull/133

**Comment by wochinge** [comment]
@tczekajlo Do you have time for a short review?

**Review by tczekajlo — APPROVED** [review]
LGTM, @wochinge thanks a lot for taking care of it 🙌🏻

**Comment by wochinge** [comment]
@tczekajlo the state ` Test the deployment of the chart ` keeps in failing though it passed successfully yesterday. Any ideas?

**Comment by wochinge** [comment]
it worked this time 🤷🏻

**Pull request merged**
