### PR TITLE
add loadBalancerSourceRanges to nginx service

### PR DESCRIPTION
**Pull request by melindaloubser1**
Add the option to specify loadBalancerSourceRanges in values for AWS deployments

### CODE REVIEW

**Review by tczekajlo — APPROVED** [review]
@melindaloubser1 You have to bump up the chart version :D

**Comment by melindaloubser1** [comment]
Ah yes🙈

**Comment by melindaloubser1** [comment]
Maybe we could add a reminder to the PR template?

**Comment by tczekajlo** [comment]
> Maybe we could add a reminder to the PR template?

There used to be a check for it. We'll take look at it, thanks 🙌🏻

**Pull request merged**
