### PR TITLE
feat(kafka): add setup for helm charts

### PR DESCRIPTION
**Pull request by mesmerx**

### CODE REVIEW

**Comment by mesmerx** [comment]
as i can understand rasa-x always need one of kafka or rabbitmq enabled, so install is separated and enable it's like if rabbit is enable so kafka is not, and if rabbit is not enabled kafka is, or i'm wrong? @tczekajlo

**Comment by melindaloubser1** [comment]
@mesmerx You are correct that one of either RabbitMQ or Kafka is required. See here  https://github.com/RasaHQ/rasa-x-helm/issues/207#issuecomment-934400749 for a conclusion of the discussion, whether Kafka should get its own section or not.

**Comment by melindaloubser1** [comment]
However, since your PR would make it possible to launch kafka as part of the chart, this is slightly different. @tczekajlo Do we want to reconsider adding kafka to the charts natively?

**Comment by melindaloubser1** [comment]
Confirmed that we're not going to be adding additional external components to the chart. https://github.com/RasaHQ/rasa-x-helm/issues/207#issuecomment-986518278.

**Pull request closed without merging**
