### PR TITLE
remove LOCAL_MODE env variable

### PR DESCRIPTION
**Pull request by chkoss**
[This PR](https://github.com/RasaHQ/rasa-x/pull/2494) removes the environment variable `LOCAL_MODE` in Rasa X. The variable should therefore not be set in the helm charts anymore.

### CODE REVIEW

**Comment by wochinge** [comment]
@chkoss I'd actually keep the LOCAL_MODE variable for legacy reasons. Users might want to run the latest Rasa X helm chart with an older Rasa X version and then things would break.

**Comment by chkoss** [comment]
@wochinge Makes sense. Do you think we should add a comment that the variable doesn't exist anymore since Rasa 0.28? Otherwise someone looking at the files might think that it does.

**Comment by wochinge** [comment]
That's a great idea! Let's do that 👍

**Comment by wochinge** [comment]
I merged despite the failing check because we don't need to release a new version / bump the version number of the chart for the comment

**Pull request merged**
